import { usePageDict, type PageDict } from './pageDict';

const DICT: PageDict = {
  qbName: { en: 'QuickBooks Online', ar: 'QuickBooks أونلاين', ru: 'QuickBooks Online', de: 'QuickBooks Online', it: 'QuickBooks Online', hi: 'QuickBooks ऑनलाइन', ur: 'QuickBooks آن لائن', ja: 'QuickBooks Online', zh: 'QuickBooks Online' },
  sageName: { en: 'Sage', ar: 'Sage ساج', ru: 'Sage', de: 'Sage', it: 'Sage', hi: 'Sage', ur: 'Sage', ja: 'Sage', zh: 'Sage' },
  subtitle: { en: 'Accounting software integration — QuickBooks & Sage', ar: 'ربط برامج المحاسبة — QuickBooks & Sage', ru: 'Интеграция бухгалтерских программ — QuickBooks & Sage', de: 'Integration von Buchhaltungssoftware — QuickBooks & Sage', it: 'Integrazione dei software contabili — QuickBooks & Sage', hi: 'लेखा सॉफ्टवेयर इंटीग्रेशन — QuickBooks और Sage', ur: 'اکاؤنٹنگ سافٹ ویئر انٹیگریشن — QuickBooks اور Sage', ja: '会計ソフト連携 — QuickBooks & Sage', zh: '会计软件集成 — QuickBooks 和 Sage' },
  betaWarning: { en: '⚠️ Simulation mode — CSV/QBO export ready, live sync needs a server OAuth', ar: '⚠️ وضع تجريبي — التصدير CSV/QBO جاهز، المزامنة المباشرة تحتاج OAuth خادم', ru: '⚠️ Демонстрационный режим — экспорт CSV/QBO готов, прямая синхронизация требует серверного OAuth', de: '⚠️ Simulationsmodus — CSV/QBO-Export bereit, Live-Sync benötigt Server-OAuth', it: '⚠️ Modalità simulazione — esportazione CSV/QBO pronta, la sincronizzazione live richiede OAuth server', hi: '⚠️ सिमुलेशन मोड — CSV/QBO निर्यात तैयार, लाइव सिंक के लिए सर्वर OAuth आवश्यक', ur: '⚠️ تجرباتی موڈ — CSV/QBO ایکسپورٹ تیار، لائیو سنک کے لیے سرور OAuth درکار', ja: '⚠️ シミュレーションモード — CSV/QBOエクスポート準備済み、ライブ同期にはサーバーOAuthが必要', zh: '⚠️ 模拟模式 — CSV/QBO 导出已就绪，实时同步需要服务器 OAuth' },
  tabPlatforms: { en: 'Platforms', ar: 'المنصات', ru: 'Платформы', de: 'Plattformen', it: 'Piattaforme', hi: 'प्लेटफ़ॉर्म', ur: 'پلیٹ فارمز', ja: 'プラットフォーム', zh: '平台' },
  tabSettings: { en: 'Settings', ar: 'الإعدادات', ru: 'Настройки', de: 'Einstellungen', it: 'Impostazioni', hi: 'सेटिंग्स', ur: 'ترتیبات', ja: '設定', zh: '设置' },
  tabExport: { en: 'Export', ar: 'تصدير', ru: 'Экспорт', de: 'Export', it: 'Esporta', hi: 'निर्यात', ur: 'ایکسپورٹ', ja: 'エクスポート', zh: '导出' },
  stConnected: { en: 'Connected', ar: 'متصل', ru: 'Подключено', de: 'Verbunden', it: 'Connesso', hi: 'कनेक्टेड', ur: 'منسلک', ja: '接続済み', zh: '已连接' },
  stSyncing: { en: 'Syncing…', ar: 'جاري المزامنة…', ru: 'Синхронизация…', de: 'Synchronisiere…', it: 'Sincronizzando…', hi: 'सिंक हो रहा है…', ur: 'سنک جاری…', ja: '同期中…', zh: '正在同步…' },
  stDisconnected: { en: 'Disconnected', ar: 'غير متصل', ru: 'Не подключено', de: 'Getrennt', it: 'Disconnesso', hi: 'डिस्कनेक्टेड', ur: 'منقطع', ja: '未接続', zh: '未连接' },
  lastSyncLabel: { en: 'Last sync: {time}', ar: 'آخر مزامنة: {time}', ru: 'Последняя синхронизация: {time}', de: 'Letzte Synchronisierung: {time}', it: 'Ultima sincronizzazione: {time}', hi: 'अंतिम सिंक: {time}', ur: 'آخری سنک: {time}', ja: '最終同期: {time}', zh: '上次同步：{time}' },
  syncedRecords: { en: '✓ Synced {count} records at {time}', ar: '✓ تمت مزامنة {count} سجلات في {time}', ru: '✓ Синхронизировано {count} записей в {time}', de: '✓ {count} Datensätze um {time} synchronisiert', it: '✓ Sincronizzati {count} record alle {time}', hi: '✓ {time} पर {count} रिकॉर्ड सिंक हुए', ur: '✓ {time} پر {count} ریکارڈز سنک ہوئے', ja: '✓ {time} に{count}件を同期しました', zh: '✓ 已在 {time} 同步 {count} 条记录' },
  connect: { en: 'Connect', ar: 'Connect / ربط', ru: 'Подключить', de: 'Verbinden', it: 'Connetti', hi: 'कनेक्ट करें', ur: 'منسلک کریں', ja: '接続', zh: '连接' },
  syncNow: { en: 'Sync Now', ar: 'Sync Now / مزامنة الآن', ru: 'Синхронизировать сейчас', de: 'Jetzt synchronisieren', it: 'Sincronizza ora', hi: 'अभी सिंक करें', ur: 'ابھی سنک کریں', ja: '今すぐ同期', zh: '立即同步' },
  disconnectSync: { en: 'Disconnect', ar: 'Disconnect / قطع الربط', ru: 'Отключить', de: 'Trennen', it: 'Disconnetti', hi: 'डिस्कनेक्ट करें', ur: 'منقطع کریں', ja: '切断', zh: '断开' },
  simulationNote: { en: 'Note: This is a simulation interface — QuickBooks uses OAuth 2.0 and Sage uses API key authentication.', ar: 'ملاحظة: واجهة محاكاة — QuickBooks يستخدم OAuth 2.0 و Sage يستخدم مفتاح API', ru: 'Примечание: имитационный интерфейс — QuickBooks использует OAuth 2.0, Sage — ключ API.', de: 'Hinweis: Simulationsoberfläche — QuickBooks nutzt OAuth 2.0 und Sage einen API-Key.', it: 'Nota: interfaccia di simulazione — QuickBooks usa OAuth 2.0 e Sage l\'autenticazione con chiave API.', hi: 'नोट: यह एक सिमुलेशन इंटरफ़ेस है — QuickBooks OAuth 2.0 और Sage API कुंजी प्रमाणीकरण का उपयोग करता है।', ur: 'نوٹ: یہ ایک تجرباتی انٹرفیس ہے — QuickBooks OAuth 2.0 استعمال کرتا ہے اور Sage API کلید تصدیق۔', ja: '注記: これはシミュレーションインターフェースです — QuickBooksはOAuth 2.0、SageはAPIキー認証を使用します。', zh: '注意：这是一个模拟界面 — QuickBooks 使用 OAuth 2.0，Sage 使用 API 密钥认证。' },
  dataTypesSub: { en: 'Data types to sync', ar: 'أنواع البيانات للمزامنة', ru: 'Типы данных для синхронизации', de: 'Zu synchronisierende Datentypen', it: 'Tipi di dati da sincronizzare', hi: 'सिंक करने योग्य डेटा प्रकार', ur: 'سنک کرنے کے لیے ڈیٹا کی اقسام', ja: '同期するデータ種別', zh: '要同步的数据类型' },
  dtInvoices: { en: 'Invoices', ar: 'الفواتير', ru: 'Счета', de: 'Rechnungen', it: 'Fatture', hi: 'चालान', ur: 'انوائسز', ja: '請求書', zh: '发票' },
  dtPayments: { en: 'Payments', ar: 'المدفوعات', ru: 'Платежи', de: 'Zahlungen', it: 'Pagamenti', hi: 'भुगतान', ur: 'ادائیگیاں', ja: '支払い', zh: '付款' },
  dtPurchaseOrders: { en: 'Purchase Orders', ar: 'طلبات الشراء', ru: 'Заказы на закупку', de: 'Bestellungen', it: 'Ordini di acquisto', hi: 'क्रय आदेश', ur: 'خریداری کے آرڈرز', ja: '発注書', zh: '采购订单' },
  dtExpenses: { en: 'Expenses', ar: 'المصاريف', ru: 'Расходы', de: 'Ausgaben', it: 'Spese', hi: 'खर्चे', ur: 'اخراجات', ja: '経費', zh: '费用' },
  freqSub: { en: 'Auto-Sync frequency', ar: 'تكرار المزامنة التلقائية', ru: 'Частота автосинхронизации', de: 'Häufigkeit der automatischen Synchronisierung', it: 'Frequenza di sincronizzazione automatica', hi: 'ऑटो-सिंक आवृत्ति', ur: 'خودکار سنک فریکوئنسی', ja: '自動同期頻度', zh: '自动同步频率' },
  freqDaily: { en: 'Daily', ar: 'يومي', ru: 'Ежедневно', de: 'Täglich', it: 'Giornaliero', hi: 'दैनिक', ur: 'روزانہ', ja: '毎日', zh: '每日' },
  freqWeekly: { en: 'Weekly', ar: 'أسبوعي', ru: 'Еженедельно', de: 'Wöchentlich', it: 'Settimanale', hi: 'साप्ताहिक', ur: 'ہفتہ وار', ja: '毎週', zh: '每周' },
  freqMonthly: { en: 'Monthly', ar: 'شهري', ru: 'Ежемесячно', de: 'Monatlich', it: 'Mensile', hi: 'मासिक', ur: 'ماہانہ', ja: '毎月', zh: '每月' },
  firebaseNote: { en: 'Settings are saved automatically to your account via Firebase.', ar: 'يتم حفظ الإعدادات تلقائياً في حسابك عبر Firebase', ru: 'Настройки автоматически сохраняются в вашей учётной записи через Firebase.', de: 'Einstellungen werden automatisch über Firebase in Ihrem Konto gespeichert.', it: 'Le impostazioni vengono salvate automaticamente nel tuo account tramite Firebase.', hi: 'सेटिंग्स Firebase के ज़रिए आपके खाते में स्वचालित रूप से सहेजी जाती हैं।', ur: 'ترتیبات Firebase کے ذریعے آپ کے اکاؤنٹ میں خود بخود محفوظ ہو جاتی ہیں۔', ja: '設定はFirebase経由でアカウントに自動保存されます。', zh: '设置会通过 Firebase 自动保存到您的账户。' },
  exportSub: { en: 'Export accounting data as CSV or QBO', ar: 'تصدير البيانات المحاسبية بصيغة CSV أو QBO', ru: 'Экспорт бухгалтерских данных в CSV или QBO', de: 'Buchhaltungsdaten als CSV oder QBO exportieren', it: 'Esporta i dati contabili come CSV o QBO', hi: 'लेखा डेटा को CSV या QBO के रूप में निर्यात करें', ur: 'اکاؤنٹنگ ڈیٹا CSV یا QBO کی صورت میں ایکسپورٹ کریں', ja: '会計データをCSVまたはQBOでエクスポート', zh: '以 CSV 或 QBO 格式导出会计数据' },
  includedData: { en: 'Included data:', ar: 'البيانات المشمولة:', ru: 'Включённые данные:', de: 'Enthaltene Daten:', it: 'Dati inclusi:', hi: 'शामिल डेटा:', ur: 'شامل کردہ ڈیٹا:', ja: '含まれるデータ:', zh: '包含的数据：' },
  noDataTypes: { en: 'No data types selected', ar: 'اختر أنواع البيانات من الإعدادات', ru: 'Не выбраны типы данных', de: 'Keine Datentypen ausgewählt', it: 'Nessun tipo di dati selezionato', hi: 'कोई डेटा प्रकार चयनित नहीं', ur: 'کوئی ڈیٹا قسم منتخب نہیں', ja: 'データ種別が選択されていません', zh: '未选择数据类型' },
  csvFile: { en: 'CSV file', ar: 'ملف CSV', ru: 'Файл CSV', de: 'CSV-Datei', it: 'File CSV', hi: 'CSV फ़ाइल', ur: 'CSV فائل', ja: 'CSVファイル', zh: 'CSV 文件' },
  qboFile: { en: 'QuickBooks file', ar: 'ملف QuickBooks', ru: 'Файл QuickBooks', de: 'QuickBooks-Datei', it: 'File QuickBooks', hi: 'QuickBooks फ़ाइल', ur: 'QuickBooks فائل', ja: 'QuickBooksファイル', zh: 'QuickBooks 文件' },
  formatNote: { en: 'CSV: Compatible with Excel, Google Sheets and most accounting tools — QBO: can be imported directly into QuickBooks Desktop or Online.', ar: 'CSV: متوافق مع Excel و Google Sheets — QBO: يمكن استيراده مباشرة في QuickBooks Desktop أو Online', ru: 'CSV: совместим с Excel, Google Sheets и большинством бухгалтерских программ — QBO: можно импортировать напрямую в QuickBooks Desktop или Online.', de: 'CSV: Kompatibel mit Excel, Google Sheets und den meisten Buchhaltungsprogrammen — QBO: kann direkt in QuickBooks Desktop oder Online importiert werden.', it: 'CSV: compatibile con Excel, Google Sheets e la maggior parte dei software contabili — QBO: può essere importato direttamente in QuickBooks Desktop o Online.', hi: 'CSV: Excel, Google Sheets और अधिकांश लेखा टूल्स के साथ संगत — QBO: सीधे QuickBooks Desktop या Online में आयात किया जा सकता है।', ur: 'CSV: Excel, Google Sheets اور زیادہ تر اکاؤنٹنگ ٹولز کے ساتھ مطابقت رکھتا ہے — QBO: براہ راست QuickBooks Desktop یا Online میں امپورٹ کیا جا سکتا ہے۔', ja: 'CSV: Excel、Google Sheets、ほとんどの会計ツールと互換 — QBO: QuickBooks DesktopまたはOnlineに直接インポートできます。', zh: 'CSV: 兼容 Excel、Google Sheets 及大多数会计工具 — QBO: 可直接导入 QuickBooks Desktop 或 Online。' },
};

export type AccountingDictKey = keyof typeof DICT;

export function useAccountingDict() {
  return usePageDict(DICT);
}