import { usePageDict, type PageDict } from './pageDict';

const DICT: PageDict = {
  dhTitle: { en: '🔌 Peripheral Devices', ar: '🔌 الأجهزة الطرفية · Peripheral Devices', ru: '🔌 Периферийные устройства', de: '🔌 Peripheriegeräte', it: '🔌 Dispositivi periferici', hi: '🔌 बाह्य उपकरण', ur: '🔌 پیریفرل ڈیوائسز', ja: '🔌 周辺機器', zh: '🔌 外围设备' },
  intro1: { en: 'All these devices are ', ar: 'كل الأجهزة دي ', ru: 'Все эти устройства ', de: 'Alle diese Geräte sind ', it: 'Tutti questi dispositivi sono ', hi: 'ये सभी उपकरण ', ur: 'یہ تمام ڈیوائسز ', ja: 'これらの機器はすべて', zh: '所有这些设备都是' },
  optionalWord: { en: 'optional', ar: 'اختيارية', ru: 'необязательны', de: 'optional', it: 'opzionali', hi: 'वैकल्पिक', ur: 'اختیاری', ja: 'オプション', zh: '可选的' },
  intro2: { en: ' — the system works fully without them. Connect a device when available at the plant and its features activate automatically.', ar: ' — النظام كامل يعمل بدونها. وصّل الجهاز لما يكون موجود في المحطة وخصائصه هتتفعل تلقائياً.', ru: ' — система полностью работает и без них. Подключите устройство, когда оно есть на станции, и его функции активируются автоматически.', de: ' — das System funktioniert vollständig auch ohne sie. Schließen Sie ein Gerät an, wenn es im Werk vorhanden ist, und seine Funktionen werden automatisch aktiviert.', it: ' — il sistema funziona completamente anche senza. Collega un dispositivo quando presente nell\'impianto e le sue funzioni si attivano automaticamente.', hi: ' — सिस्टम इनके बिना पूरी तरह काम करता है। जब उपकरण प्लांट में उपलब्ध हो तो कनेक्ट करें और इसकी सुविधाएँ स्वचालित रूप से सक्रिय हो जाएँगी।', ur: ' — سسٹم ان کے بغیر مکمل کام کرتا ہے۔ جب ڈیوائس پلانٹ میں موجود ہو تو جوڑیں اور اس کی خصوصیات خود بخود فعال ہو جائیں گی۔', ja: ' — システムはそれらなしでも完全に動作します。プラントにある機器を接続すると機能が自動で有効になります。', zh: ' — 没有它们系统也能完整运行。当搅拌站有设备时连接它，其功能将自动激活。' },
  loadingDevices: { en: '⏳ Loading device status...', ar: '⏳ جاري تحميل حالة الأجهزة...', ru: '⏳ Загрузка состояния устройств...', de: '⏳ Gerätestatus wird geladen...', it: '⏳ Caricamento stato dispositivi...', hi: '⏳ उपकरण स्थिति लोड हो रही है...', ur: '⏳ ڈیوائس کی حالت لوڈ ہو رہی ہے...', ja: '⏳ デバイス状態を読み込み中...', zh: '⏳ 正在加载设备状态...' },
  lastCheck: { en: 'Last checked: {time}', ar: 'آخر تحقق: {time}', ru: 'Последняя проверка: {time}', de: 'Zuletzt geprüft: {time}', it: 'Ultimo controllo: {time}', hi: 'अंतिम जाँच: {time}', ur: 'آخری جانچ: {time}', ja: '最終確認: {time}', zh: '上次检查：{time}' },
  connectedOn: { en: '✅ Connected', ar: '✅ متصل', ru: '✅ Подключено', de: '✅ Verbunden', it: '✅ Connesso', hi: '✅ कनेक्टेड', ur: '✅ منسلک', ja: '✅ 接続済み', zh: '✅ 已连接' },
  connectBtn: { en: '🔌 Connect', ar: '🔌 توصيل', ru: '🔌 Подключить', de: '🔌 Verbinden', it: '🔌 Connetti', hi: '🔌 कनेक्ट करें', ur: '🔌 جوڑیں', ja: '🔌 接続', zh: '🔌 连接' },
  badgeConnected: { en: '🔌 Connected to device', ar: '🔌 متصل بالجهاز', ru: '🔌 Подключено к устройству', de: '🔌 Mit Gerät verbunden', it: '🔌 Collegato al dispositivo', hi: '🔌 डिवाइस से कनेक्टेड', ur: '🔌 ڈیوائس سے منسلک', ja: '🔌 デバイスに接続中', zh: '🔌 已连接到设备' },
  badgeNoDevice: { en: '📴 Working without device', ar: '📴 يعمل بدون جهاز', ru: '📴 Работает без устройства', de: '📴 Arbeitet ohne Gerät', it: '📴 Funziona senza dispositivo', hi: '📴 डिवाइस के बिना काम कर रहा', ur: '📴 ڈیوائس کے بغیر کام کر رہا', ja: '📴 デバイスなしで稼働中', zh: '📴 无设备运行中' },
  toastConnected: { en: '✅ {name} connected — its related features are enabled', ar: '✅ تم توصيل {name} — الخصائص المرتبطة اشتغلت', ru: '✅ {name} подключено — связанные функции включены', de: '✅ {name} verbunden — die zugehörigen Funktionen sind aktiviert', it: '✅ {name} collegato — le funzioni correlate sono attive', hi: '✅ {name} कनेक्ट हुआ — संबंधित सुविधाएँ सक्रिय हैं', ur: '✅ {name} منسلک ہو گیا — متعلقہ خصوصیات فعال ہو گئیں', ja: '✅ {name} を接続 — 関連機能が有効になりました', zh: '✅ {name} 已连接 — 相关功能已启用' },
  toastDisconnected: { en: '📴 {name} disconnected — the system runs fine without it', ar: '📴 تم فصل {name} — النظام يشتغل عادي بدونها', ru: '📴 {name} отключено — система работает нормально и без него', de: '📴 {name} getrennt — das System funktioniert auch ohne es einwandfrei', it: '📴 {name} disconnesso — il sistema funziona comunque', hi: '📴 {name} डिस्कनेक्ट हुआ — सिस्टम इसके बिना ठीक चलता है', ur: '📴 {name} منقطع ہو گیا — سسٹم اس کے بغیر بھی ٹھیک چلتا ہے', ja: '📴 {name} を切断 — システムはなしでも正常に動作します', zh: '📴 {name} 已断开 — 系统无需它也可正常运行' },
  devBatch: { en: 'Batch Controller', ar: 'متحكم المحطة', ru: 'Контроллер завода', de: 'Werksteuerung', it: 'Controller dell\'impianto', hi: 'बैच कंट्रोलर', ur: 'بیچ کنٹرولر', ja: 'バッチコントローラー', zh: '批控器' },
  devDashcam: { en: 'Fleet Dashcam', ar: 'داش كام الأسطول', ru: 'Видеорегистратор автопарка', de: 'Flotten-Dashcam', it: 'Dashcam flotta', hi: 'फ्लीट डैशकैम', ur: 'فلیٹ ڈیش کیم', ja: '車両ドライブレコーダー', zh: '车队行车记录仪' },
  devAccounting: { en: 'Accounting Software', ar: 'البرنامج المحاسبي', ru: 'Бухгалтерская программа', de: 'Buchhaltungssoftware', it: 'Software contabile', hi: 'लेखा सॉफ्टवेयर', ur: 'اکاؤنٹنگ سافٹ ویئر', ja: '会計ソフト', zh: '会计软件' },
  devGps: { en: 'GPS Trackers', ar: 'متتبعات GPS', ru: 'GPS-трекеры', de: 'GPS-Tracker', it: 'Tracker GPS', hi: 'GPS ट्रैकर', ur: 'GPS ٹریکرز', ja: 'GPSトラッカー', zh: 'GPS 追踪器' },
  devWeighbridge: { en: 'Weighbridge', ar: 'قبّان الوزن (بسكول)', ru: 'Автовесы', de: 'Brückenwaage', it: 'Ponte a pesare', hi: 'वेटब्रिज', ur: 'ویٹ برج', ja: 'トラックスケール', zh: '地磅' },
  descBatch: { en: 'Command Alkon / Liebherr / Sicom — live batch feed', ar: 'Command Alkon / Liebherr / Sicom — بث مباشر للدفعات', ru: 'Command Alkon / Liebherr / Sicom — прямая трансляция партий', de: 'Command Alkon / Liebherr / Sicom — Live-Chargen-Feed', it: 'Command Alkon / Liebherr / Sicom — flusso live dei lotti', hi: 'Command Alkon / Liebherr / Sicom — लाइव बैच फ़ीड', ur: 'Command Alkon / Liebherr / Sicom — بیچز کی لائیو فیڈ', ja: 'Command Alkon / Liebherr / Sicom — バッチのライブ配信', zh: 'Command Alkon / Liebherr / Sicom — 批次实时信息' },
  descDashcam: { en: 'Truck cameras + event detection', ar: 'كاميرات الشاحنات + كشف الأحداث', ru: 'Камеры грузовиков + обнаружение событий', de: 'LKW-Kameras + Ereigniserkennung', it: 'Telecamere camion + rilevamento eventi', hi: 'ट्रक कैमरे + ईवेंट पहचान', ur: 'ٹرک کیمرے + ایونٹ کی شناخت', ja: 'トラックカメラ＋イベント検知', zh: '卡车摄像头 + 事件检测' },
  descAccounting: { en: 'QuickBooks / Sage invoice & payment sync', ar: 'QuickBooks / Sage مزامنة الفواتير والمدفوعات', ru: 'QuickBooks / Sage синхронизация счетов и платежей', de: 'QuickBooks / Sage Rechnungs- und Zahlungssynchronisierung', it: 'QuickBooks / Sage sincronizzazione fatture e pagamenti', hi: 'QuickBooks / Sage चालान और भुगतान सिंक', ur: 'QuickBooks / Sage انوائسز اور ادائیگیوں کا سنک', ja: 'QuickBooks / Sage 請求書・支払い同期', zh: 'QuickBooks / Sage 发票与付款同步' },
  descGps: { en: 'Tracking devices on trucks and equipment', ar: 'أجهزة التتبع في الشاحنات والمعدات', ru: 'Трекеры на грузовиках и оборудовании', de: 'Tracker an LKW und Geräten', it: 'Tracker su camion e attrezzature', hi: 'ट्रकों और उपकरणों पर ट्रैकिंग डिवाइस', ur: 'ٹرکوں اور آلات پر ٹریکنگ ڈیوائسز', ja: 'トラック・機材の追跡デバイス', zh: '卡车和设备上的追踪设备' },
  descWeighbridge: { en: 'Truck scale connection (optional — manual works)', ar: 'ربط ميزان السيارات (اختياري — اليدوي شغال)', ru: 'Подключение автовесов (опционально — работает вручную)', de: 'LKW-Waagen-Anbindung (optional — manuell funktioniert)', it: 'Collegamento bilancia camion (opzionale — manuale funziona)', hi: 'ट्रक तराजू कनेक्शन (वैकल्पिक — मैनुअल काम करता है)', ur: 'ٹرک اسکیل کنکشن (اختیاری — دستی کام کرتا ہے)', ja: 'トラックスケール接続（オプション — 手動でも動作）', zh: '卡车地磅连接（可选 — 手动也有效）' },
};

export type DeviceHubDictKey = keyof typeof DICT;

export function useDeviceHubDict() {
  return usePageDict(DICT);
}