import { usePageDict, type PageDict } from './pageDict';

const DICT: PageDict = {
  errBadCredentials: { en: 'Email / phone number or password is incorrect', ar: 'البريد الإلكتروني / رقم الهاتف أو كلمة المرور غير صحيحة', ru: 'Электронная почта / телефон или пароль неверны', de: 'E-Mail / Telefonnummer oder Passwort ist falsch', it: 'Email / numero di telefono o password non validi', hi: 'ईमेल / फ़ोन नंबर या पासवर्ड गलत है', ur: 'ای میل / فون نمبر یا پاس ورڈ غلط ہے', ja: 'メールアドレス／電話番号またはパスワードが正しくありません', zh: '邮箱/电话号码或密码不正确' },
  errGeneric: { en: 'An error occurred while signing in', ar: 'حدث خطأ أثناء تسجيل الدخول', ru: 'Произошла ошибка при входе', de: 'Beim Anmelden ist ein Fehler aufgetreten', it: 'Si è verificato un errore durante l\'accesso', hi: 'साइन इन के दौरान एक त्रुटि हुई', ur: 'سائن ان کے دوران ایک خرابی ہوئی', ja: 'ログイン中にエラーが発生しました', zh: '登录时发生错误' },
  loginTitle: { en: 'Sign in', ar: 'تسجيل الدخول', ru: 'Вход', de: 'Anmelden', it: 'Accedi', hi: 'साइन इन करें', ur: 'سائن ان', ja: 'ログイン', zh: '登录' },
  subtitle: { en: 'Concrete plant management system — FimtoSoft', ar: 'نظام إدارة مصانع الخرسانة — FimtoSoft', ru: 'Система управления бетонными заводами — FimtoSoft', de: 'Betonwerk-Verwaltungssystem — FimtoSoft', it: 'Sistema di gestione impianti di calcestruzzo — FimtoSoft', hi: 'कंक्रीट प्लांट प्रबंधन प्रणाली — FimtoSoft', ur: 'کنکریٹ پلانٹ مینجمنٹ سسٹم — FimtoSoft', ja: 'コンクリートプラント管理システム — FimtoSoft', zh: '混凝土搅拌站管理系统 — FimtoSoft' },
  unifiedNote: { en: '🔐 Your credentials are now unified with the main concrete system (central backend)', ar: '🔐 بياناتك الآن موحدة مع نظام الخرسانة الرئيسي (الباكند المركزي)', ru: '🔐 Ваши учётные данные теперь едины с основной бетонной системой (центральный бэкенд)', de: '🔐 Ihre Zugangsdaten sind jetzt mit dem Hauptsystem (zentrales Backend) vereinheitlicht', it: '🔐 Le tue credenziali ora sono unificate con il sistema principale (backend centrale)', hi: '🔐 आपकी साख अब मुख्य कंक्रीट सिस्टम (केंद्रीय बैकएंड) के साथ एकीकृत हैं', ur: '🔐 آپ کی معلومات اب مرکزی کنکریٹ سسٹم (سنٹرل بیک اینڈ) کے ساتھ یکجا ہیں', ja: '🔐 認証情報はメインのコンクリートシステム（中央バックエンド）と統合されました', zh: '🔐 您的凭据现已与主混凝土系统（中央后端）统一' },
  identifierLabel: { en: 'Email or phone number', ar: 'البريد الإلكتروني أو رقم الهاتف', ru: 'Электронная почта или номер телефона', de: 'E-Mail oder Telefonnummer', it: 'Email o numero di telefono', hi: 'ईमेल या फ़ोन नंबर', ur: 'ای میل یا فون نمبر', ja: 'メールアドレスまたは電話番号', zh: '邮箱或电话号码' },
  idPlaceholder: { en: 'you@example.com or +9665xxxxxxxx', ar: 'you@example.com  أو  +9665xxxxxxxx', ru: 'you@example.com или +9665xxxxxxxx', de: 'you@example.com oder +9665xxxxxxxx', it: 'you@example.com o +9665xxxxxxxx', hi: 'you@example.com या +9665xxxxxxxx', ur: 'you@example.com یا +9665xxxxxxxx', ja: 'you@example.com または +9665xxxxxxxx', zh: 'you@example.com 或 +9665xxxxxxxx' },
  passwordLabel: { en: 'Password', ar: 'كلمة المرور', ru: 'Пароль', de: 'Passwort', it: 'Password', hi: 'पासवर्ड', ur: 'پاس ورڈ', ja: 'パスワード', zh: '密码' },
  passwordPh: { en: 'Password', ar: 'كلمة المرور', ru: 'Пароль', de: 'Passwort', it: 'Password', hi: 'पासवर्ड', ur: 'پاس ورڈ', ja: 'パスワード', zh: '密码' },
  loggingIn: { en: 'Signing in...', ar: 'جاري تسجيل الدخول...', ru: 'Вход...', de: 'Anmeldung läuft...', it: 'Accesso in corso...', hi: 'साइन इन हो रहा है...', ur: 'سائن ان جاری...', ja: 'ログイン中...', zh: '正在登录...' },
  rememberMe: { en: '💾 Save login data on this device', ar: '💾 حفظ بيانات الدخول على هذا الجهاز', ru: '💾 Сохранить данные входа на этом устройстве', de: '💾 Anmeldedaten auf diesem Gerät speichern', it: '💾 Salva i dati di accesso su questo dispositivo', hi: '💾 इस डिवाइस पर लॉगिन डेटा सहेजें', ur: '💾 اس ڈیوائس پر لاگ ان ڈیٹا محفوظ کریں', ja: '💾 このデバイスにログイン情報を保存', zh: '💾 在此设备上保存登录信息' },
  loginBtn: { en: 'Sign in', ar: 'تسجيل الدخول', ru: 'Войти', de: 'Anmelden', it: 'Accedi', hi: 'साइन इन करें', ur: 'سائن ان', ja: 'ログイン', zh: '登录' },
  accountsNote: { en: 'Account creation is done from the owner control panel — contact the system administrator to get an account', ar: 'إنشاء الحسابات يتم من لوحة تحكم المالك — تواصل مع مدير النظام للحصول على حساب', ru: 'Учётные записи создаются с панели управления владельца — обратитесь к администратору системы', de: 'Konten werden über das Bedienfeld des Eigentümers erstellt — wenden Sie sich an den Systemadministrator', it: 'La creazione degli account avviene dal pannello del proprietario — contatta l\'amministratore di sistema', hi: 'खातों का निर्माण मालिक नियंत्रण पैनल से होता है — खाता पाने हेतु सिस्टम एडमिनिस्ट्रेटर से संपर्क करें', ur: 'اکاؤنٹ بنانا مالک کنٹرول پینل سے ہوتا ہے — اکاؤنٹ حاصل کرنے کے لیے سسٹم ایڈمنسٹریٹر سے رابطہ کریں', ja: 'アカウント作成はオーナー管理パネルから行います — アカウントが必要な場合はシステム管理者にご連絡ください', zh: '账户由所有者控制面板创建 — 请联系系统管理员获取账户' },
};

export function useLoginRegisterDict() {
  return usePageDict(DICT);
}