import { usePageDict, type PageDict } from './pageDict';

const DICT: PageDict = {
  quotaBlocked: { en: '🚫 Your storage space is fully used ({quota} MB)', ar: '🚫 تم استهلاك مساحة التخزين الخاصة بك بالكامل ({quota} MB)', ru: '🚫 Всё дисковое пространство израсходовано ({quota} МБ)', de: '🚫 Ihr Speicherplatz ist vollständig verbraucht ({quota} MB)', it: '🚫 Lo spazio di archiviazione è completamente esaurito ({quota} MB)', hi: '🚫 आपका भंडारण स्थान पूरी तरह उपयोग हो गया ({quota} MB)', ur: '🚫 آپ کی سٹوریج جگہ مکمل طور پر استعمال ہو چکی ہے ({quota} MB)', ja: '🚫 ストレージ容量を使い切りました（{quota} MB）', zh: '🚫 您的存储空间已完全用尽（{quota} MB）' },
  quotaBlockedSub: { en: 'No more data can be saved. Contact the developer to increase your database.', ar: 'لا يمكن حفظ المزيد من البيانات. تواصل مع المبرمج لزيادة قاعدة بياناتك.', ru: 'Сохранение данных невозможно. Свяжитесь с разработчиком для увеличения базы данных.', de: 'Es können keine weiteren Daten gespeichert werden. Kontaktieren Sie den Entwickler, um Ihre Datenbank zu erweitern.', it: 'Non è possibile salvare altri dati. Contatta lo sviluppatore per aumentare il tuo database.', hi: 'और डेटा सहेजा नहीं जा सकता। डेटाबेस बढ़ाने हेतु डेवलपर से संपर्क करें।', ur: 'مزید ڈیٹا محفوظ نہیں کیا جا سکتا۔ ڈیٹا بیس بڑھانے کے لیے ڈویلپر سے رابطہ کریں۔', ja: 'これ以上データを保存できません。データベース拡張については開発者にご連絡ください。', zh: '无法保存更多数据。请联系开发者增加您的数据库。' },
  contactDev: { en: '✉️ Contact the developer', ar: '✉️ تواصل مع المبرمج', ru: '✉️ Связаться с разработчиком', de: '✉️ Entwickler kontaktieren', it: '✉️ Contatta lo sviluppatore', hi: '✉️ डेवलपर से संपर्क करें', ur: '✉️ ڈویلپر سے رابطہ کریں', ja: '✉️ 開発者に連絡', zh: '✉️ 联系开发者' },
  whatsapp: { en: '💬 WhatsApp', ar: '💬 واتساب', ru: '💬 WhatsApp', de: '💬 WhatsApp', it: '💬 WhatsApp', hi: '💬 व्हाट्सऐप', ur: '💬 واٹس ایپ', ja: '💬 WhatsApp', zh: '💬 WhatsApp' },
  storageUsage: { en: '💾 Your storage space: {used} MB of {quota} MB', ar: '💾 مساحة التخزين الخاصة بك: {used} MB من {quota} MB', ru: '💾 Ваше дисковое пространство: {used} МБ из {quota} МБ', de: '💾 Ihr Speicherplatz: {used} MB von {quota} MB', it: '💾 Il tuo spazio di archiviazione: {used} MB su {quota} MB', hi: '💾 आपका भंडारण स्थान: {quota} MB में से {used} MB', ur: '💾 آپ کی سٹوریج جگہ: {quota} MB میں سے {used} MB', ja: '💾 ストレージ容量: {quota} MB中{used} MB', zh: '💾 您的存储空间：{quota} MB 中的 {used} MB' },
  warnNearLimit: { en: '⚠️ You are close to your storage limit — if you need a larger database, contact the developer.', ar: '⚠️ اقتربت من نهاية مساحتك — إذا احتجت قاعدة أكبر تواصل مع المبرمج.', ru: '⚠️ Вы приближаетесь к лимиту — если нужна база большего размера, свяжитесь с разработчиком.', de: '⚠️ Sie nähern sich Ihrem Speicherlimit — bei Bedarf an einer größeren Datenbank kontaktieren Sie den Entwickler.', it: '⚠️ Ti stai avvicinando al limite di spazio — se ti serve un database più grande, contatta lo sviluppatore.', hi: '⚠️ आप अपनी भंडारण सीमा के करीब हैं — बड़े डेटाबेस की आवश्यकता होने पर डेवलपर से संपर्क करें।', ur: '⚠️ آپ اپنی سٹوریج حد کے قریب ہیں — بڑے ڈیٹا بیس کی ضرورت ہو تو ڈویلپر سے رابطہ کریں۔', ja: '⚠️ ストレージ上限に近づいています — 大規模なデータベースが必要な場合は開発者にご連絡ください。', zh: '⚠️ 您已接近存储限制 — 如需更大数据库，请联系开发者。' },
  remaining: { en: '{remaining} MB remaining', ar: 'تبقى لديك {remaining} MB', ru: 'Осталось {remaining} МБ', de: '{remaining} MB verbleibend', it: '{remaining} MB rimanenti', hi: '{remaining} MB शेष', ur: '{remaining} MB باقی', ja: '残り {remaining} MB', zh: '剩余 {remaining} MB' },
};

export function useQuotaBannerDict() {
  return usePageDict(DICT);
}