import { usePageDict, type PageDict } from './pageDict';

const DICT: PageDict = {
  fleetTitle: { en: '📍 Live fleet locations', ar: '📍 مواقع الأسطول المباشرة', ru: '📍 Прямое местоположение автопарка', de: '📍 Live-Standorte der Flotte', it: '📍 Posizioni flotta in tempo reale', hi: '📍 लाइव फ्लीट स्थान', ur: '📍 فلیٹ کی لائیو لوکیشنز', ja: '📍 車両のライブ位置', zh: '📍 车队实时位置' },
  gpsCount: { en: '🔌 {n} vehicles with GPS feed', ar: '🔌 {n} مركبة ببث GPS', ru: '🔌 {n} машин с GPS-трансляцией', de: '🔌 {n} Fahrzeuge mit GPS-Feed', it: '🔌 {n} veicoli con segnale GPS', hi: '🔌 {n} वाहन GPS फ़ीड के साथ', ur: '🔌 {n} گاڑیاں GPS فیڈ کے ساتھ', ja: '🔌 GPS配信中の車両 {n} 台', zh: '🔌 {n} 辆带 GPS 信息的车辆' },
  noTrackers: { en: '📴 No trackers — the map activates automatically when connected', ar: '📴 بدون متتبعات — الخريطة تتفعل تلقائياً عند التوصيل', ru: '📴 Нет трекеров — карта включится автоматически при подключении', de: '📴 Keine Tracker — die Karte aktiviert sich automatisch bei Verbindung', it: '📴 Nessun tracker — la mappa si attiva automaticamente al collegamento', hi: '📴 कोई ट्रैकर नहीं — कनेक्ट होने पर मैप स्वचालित रूप से सक्रिय होता है', ur: '📴 کوئی ٹریکر نہیں — منسلک ہوتے ہی نقشہ خود بخود فعال ہو جاتا ہے', ja: '📴 トラッカーなし — 接続するとマップが自動的に有効になります', zh: '📴 无追踪器 — 连接后地图自动激活' },
  hintPre: { en: '📡 GPS trackers are not yet connected to assets — from the admin panel → ', ar: '📡 لسه مربوطتش متتبعات GPS للأصول — من لوحة الإدارة → ', ru: '📡 GPS-трекеры ещё не подключены к активам — с панели управления → ', de: '📡 Noch keine GPS-Tracker mit den Geräten verbunden — über das Admin-Panel → ', it: '📡 I tracker GPS non sono ancora collegati alle risorse — dal pannello di amministrazione → ', hi: '📡 संपत्तियों से GPS ट्रैकर अभी कनेक्ट नहीं — प्रशासन पैनल से → ', ur: '📡 اثاثوں سے GPS ٹریکرز ابھی منسلک نہیں — ایڈمن پینل سے → ', ja: '📡 資産にGPSトラッカーが未接続 — 管理パネルから → ', zh: '📡 尚未将 GPS 追踪器连接到资产 — 从管理面板 → ' },
  peripheralDevices: { en: 'Peripheral Devices', ar: 'الأجهزة الطرفية', ru: 'Периферийные устройства', de: 'Peripheriegeräte', it: 'Dispositivi periferici', hi: 'बाह्य उपकरण', ur: 'پیریفرل ڈیوائسز', ja: '周辺機器', zh: '外围设备' },
  hintPost: { en: ' connect "GPS Trackers", set the coordinates for each asset, and the map will work on its own.', ar: ' وصّل «متتبعات GPS» وحدد الإحداثيات لكل أصل، والخريطة هتشتغل لوحدها.', ru: ' подключите «GPS-трекеры», укажите координаты для каждого актива, и карта заработает сама.', de: ' verbinden Sie „GPS-Tracker", legen Sie die Koordinaten für jedes Gerät fest, und die Karte funktioniert von selbst.', it: ' collega i "Tracker GPS", imposta le coordinate per ogni risorsa e la mappa funzionerà da sola.', hi: ' "GPS ट्रैकर" कनेक्ट करें, प्रत्येक संपत्ति के निर्देशांक निर्धारित करें, और मैप अपने आप काम करेगा।', ur: ' «GPS ٹریکرز» جوڑیں، ہر اثاثے کے لیے نقاط مقرر کریں، اور نقشہ خود کام کرے گا۔', ja: ' 「GPSトラッカー」を接続し、各資産に座標を設定すると、マップは自動で動作します。', zh: ' 连接“GPS 追踪器”，为每个资产设置坐标，地图将自动运行。' },
};

export function useWorkshopGpsMapDict() {
  return usePageDict(DICT);
}